### ISSUE TITLE
Mention electric candles as a possible alternative to real ones

### ISSUE THREAD

**Issue by SilasX** [GeneralAntilles/PetrovDay#4]
Under

- 8 candles and a lighter

We could note that electric candles could be used if flames are not allowed at the location e.g.

"Consider using electric candles if open flames are dangerous or disallowed at the venue."

**Comment by GeneralAntilles** [comment]
I added a note after the item list on the organizer guide and ceremony booklet.

> If you are not comfortable using real candles or are unable to perform the
> ceremony in a location where you can use them safely, then substitute with LED
> candles and omit the lanterns, lighter, taper, and snuffer.
>
